title = "JustCarver.com"
baseurl = "https://justcarver.com"
languageCode = "en-us"
relativeurls = true

PygmentsCodeFences = true
editor = "vim"

[taxonomies]
language = "languages"

[params]
  description = "Justin Carver's personal journey through the world of software development"
  author = "Justin Carver"
  subtitle = "Justin Carver's personal site/blog"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/project/"
    weight = 3

  [[menu.social]]
    name="GitHub"
    identifier = "github"
    url = "https://github.com/justcarver"
    pre = "<i class='fa fa-github'></i>"
    weight = 1
  [[menu.social]]
    name="Twitter"
    identifier = "twitter"
    url = "https://twitter.com/itsjustcarver"
    pre = "<i class='fa fa-twitter'></i>"
    weight = 2
  [[menu.social]]
    name="Instagram"
    identifier = "instagram"
    url = "https://www.instagram.com/itsjustcarver/"
    pre = "<i class='fa fa-instagram'></i>"
    weight = 3
  [[menu.social]]
    name="LinkedIn"
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/justincarver/"
    pre = "<i class='fa fa-linkedin-square'></i>"
    weight = 4
  [[menu.social]]
    name="Email"
    identifier = "email"
    url = "mailto:carver@justcarver.com"
    pre = "<i class='fa fa-envelope'></i>"
    weight = 5
