title = "JustCarver.com"
baseurl = "http://www.justcarver.com"
languageCode = "en-us"

PygmentsCodeFences = true
editor = "vim"

[params]
  description = "Justin Carver's personal journey through the world of software development"
  author = "Justin Carver"
  subtitle = "Justin Carver's personal site/blog"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/post/"
    weight = 2

  [[menu.social]]
    name="GitHub"
    identifier = "github"
    url = "https://github.com/justcarver"
    weight = 1
  [[menu.social]]
    name="Twitter"
    identifier = "twitter"
    url = "https://twitter.com/itsjustcarver"
    weight = 2
  [[menu.social]]
    name="Instagram"
    identifier = "instagram"
    url = "https://www.instagram.com/itsjustcarver/"
    weight = 3
  [[menu.social]]
    name="LinkedIn"
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/justincarver/"
    weight = 4
